import draft
a = int(input('input starting point: '))
b = int(input('input ending point: '))
segment = draft.segment(a, b)
print('segment: ', segment)
emptiness = draft.isempty(segment)
print('is empty?', emptiness)
makeempty = draft.segmempty(segment, emptiness)
print(makeempty)
a1 = int(input('input a1: '))
b1 = int(input('input b1: '))
a2 = int(input('input a2: '))
b2 = int(input('input b2: '))
segment1 = draft.segment(a1, b1)
segment2 = draft.segment(a2, b2)
intersection = draft.intersept(segment1, segment2)
print('intersection of s1 and s2: ', intersection)
